primary_conninfo = 'host=b100udns3 port=5432 user=replicationuser application_name=b100udns3 sslmode=verify-full passfile=''/var/lib/postgresql/.pgpass'''
recovery_target_timeline = 'latest'
primary_slot_name = 'b100udns3'
cluster_name = 'b100udns3'
